"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MANIFEST_CONTENT_TYPE = exports.PRIVATE_CONTENT_TYPE = exports.JSON_CONTENT_TYPE = exports.DEFAULT_APP_VERSION = exports.DEFAULT_APP_NAME = exports.CURRENT_ARFS_VERSION = exports.ArFS_O_11 = void 0;
exports.ArFS_O_11 = '0.11';
exports.CURRENT_ARFS_VERSION = exports.ArFS_O_11;
exports.DEFAULT_APP_NAME = 'ArDrive-Core';
exports.DEFAULT_APP_VERSION = '1.0.0';
exports.JSON_CONTENT_TYPE = 'application/json';
exports.PRIVATE_CONTENT_TYPE = 'application/octet-stream';
exports.MANIFEST_CONTENT_TYPE = 'application/x.arweave-manifest+json';
